### ISSUE TITLE
Wifi.ini not working

### ISSUE THREAD

**Issue by Dixzz** [mpurses/Sonder#3]
if, wifi is ON and it is connected
Clicking the wifi icon does not work
but if wifi is OFF it works perfectly.

**Comment by mpurses** [comment]
Sometimes the amount of tabs to perform to activate/deactivate the wifi gets thrown off (Usually because of a user click changing the first focus). Or it could also be a different system has a different setup.

First I would restart your system just to see if it works with no interaction of the Wifi manually (just using the Rainmeter skin). If it still doesn't work, click the Wifi icon in the Windows Taskbar Tray and test how many "Tabs" it takes to get to the Wifi button. If its not 4, you can change the **TurnOffWifi** variable in Variables.inc to accommodate the number of tabs:

From this section in it:
[#@#\Scripts\Send4TabKey.vbs]

I only have scripts for 3 and 4 tabs, so if its not one of those, you'll have to make a new script for that number.

Also, if it looks like the wifi window takes long to open, try changing the Wifi Open Delay in the settings.

Let me know if any of those fixes it.

**Comment by Dixzz** [comment]
It took 2 tabs and now everything works just perfect thanks again!
